name: Release to Prod

on:
  workflow_dispatch:
    tags:
      - v*.*.*
    inputs:
      runners:
        description: Choose runner to run
        type: choice
        options:
          - atc-ubuntu-latest
          - tsp-ubuntu-runner
        required: false
        default: atc-ubuntu-latest

run-name: ${{ format('Release {0} to prod-cn using {1}', github.ref_name, inputs.runners) }}

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      runners: ${{ inputs.runners }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-reusable.yaml
    secrets: inherit
    with:
      environment: prod-cn
      runners: ${{ inputs.runners }}
