name: Manual Build & Deploy in Non-Prod

on:
  workflow_dispatch:
    branches:
      - main
      - release
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
    inputs:
      environment:
        description: Choose environment to deploy
        type: choice
        options:
          - dev
          - demo
        default: dev
      runners:
        description: Choose runner to run
        type: choice
        options:
          - atc-ubuntu-latest
          - tsp-ubuntu-runner
        required: false
        default: atc-ubuntu-latest

run-name: ${{ format('Build and deploy from {0} to {1} using runners {2}', github.ref_name, inputs.environment, inputs.runners) }}

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      runners: ${{ inputs.runners }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-reusable.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      runners: ${{ inputs.runners }}
