name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: Choose environment to deploy
        type: string
        default: dev
      runners:
        description: Choose runner to run
        type: string
        default: ubuntu-latest

env:
  host: ${{ secrets.ALIYUN_HOST }}
  username: ${{ secrets.ALIYUN_USERNAME }}
  key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ${{ inputs.runners }}
    environment: ${{ inputs.environment }}    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.12.0'
    
    - name: Download from Artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
      
    - name: Deploy to Aliyun ECS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/var/www/app-auto-deploy"
        strip_components: 1