name: Vue.js CI/CD to Aliyun ECS

on:
  push:
    branches: [ main ]

jobs:
  prod-build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.12.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Prepare and deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        script: |
          # 设置变量
          DEPLOY_DIR="/var/www/app-auto-deploy"
          BACKUP_DIR="/home/blog/website_backups"
          
          # 创建备份目录（如果不存在）
          mkdir -p $BACKUP_DIR
          
          # 创建一个带时间戳的备份目录
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          BACKUP_TIMESTAMP_DIR="$BACKUP_DIR/backup_$TIMESTAMP"
          
          # 如果部署目录存在，则创建备份
          if [ -d "$DEPLOY_DIR" ]; then
            echo "Creating backup of current deployment..."
            cp -R $DEPLOY_DIR $BACKUP_TIMESTAMP_DIR
          else
            echo "No existing deployment to backup."
          fi
          
          # 确保部署目录存在并为空
          sudo mkdir -p $DEPLOY_DIR
          sudo rm -rf $DEPLOY_DIR/*
          
          # 删除超过7天的备份
          find $BACKUP_DIR -type d -mtime +7 -exec rm -rf {} +
          
          echo "Deployment directory is ready for new files."

    - name: Copy new files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/var/www/app-auto-deploy"
        strip_components: 1
        script: |
          echo "Deployment completed successfully."