name: Vue.js CI/CD to Aliyun ECS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.12.0'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        script: |
          # 创建一个临时目录
          TEMP_DIR=$(mktemp -d)
          
          # 将当前部署的内容移动到临时目录（作为备份）
          sudo mv /var/www/app-auto-deploy/* $TEMP_DIR/
          
          # 确保nginx目录存在并且为空
          sudo mkdir -p /var/www/app-auto-deploy
          sudo rm -rf /var/www/app-auto-deploy/*

    - name: Copy new files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/var/www/app-auto-deploy"
        strip_components: 1

    - name: Finalize deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        script: |
          
          # 删除超过7天的备份
          find $HOME/temp_backups -type d -mtime +7 -exec rm -rf {} +
          
          # 将这次的备份移动到备份目录
          sudo mv $TEMP_DIR $HOME/temp_backups/backup_$(date +%Y%m%d_%H%M%S)