name: Vue CI/CD to Aliyun ECS
 
on:
  push:
    branches: [ dev ]
 
jobs:
  dev-build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.12.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Aliyun ECS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/var/www/app-auto-deploy"
        strip_components: 1